### PR TITLE
Button style

### PR DESCRIPTION
**Pull request by liliakai**
Add some built-in classes to the button, use toolbarbutton instead of regular
button element, and add an svg icon.

None of these techniques are particularly well documented and I discovered them by trial and
error, searching, and looking at other extensions' code on github.

### CODE REVIEW

**Comment by liliakai** [comment]
Here's a screenshot of the result:

screen shot 2018-11-09 at 3 58 01 pm

**Comment by mfc** [comment]
amazing. does this apply for the main thunderbird toolbar as well? (with the extension installed, right-click on the bar that has "Get Messages | Write | Chat" etc. and select Customize. there should be a `Report via Suspicious Email Submitter` button you can add).

**Comment by liliakai** [comment]
It does now.

**Comment by mfc** [comment]
great, merged

**Pull request merged**
